---
# default user for the nodes. Must have SSH key-less login on the machine running the playbook
# and must have sudo password-less enabled on the host(s)

#  when: adsbexchange_install == true

ansible_user: ubuntu

# install misc services?

install_misc_services: true
install_adsb_services: true

#for use when running setup-pods-master. Fill in values from the rancher setup
rancher_token: "fhkp442xsc6c7ddv7vrqhhntcgbxqgr4mfjbczwjwkbx5wvq579dj9"
rancher_checksum: "15e3e28a2dd4deb1d657ab3d9c01a501a5d7978dfbcff0ba5710819d85a00079"
rancher_server: https://192.168.31.30:8443
rancher_image: rancher/rancher:v2.5.1
rancher_agent: rancher/rancher-agent:v2.5.1

#the node hostname, from the inventory file, that has 1090 RTLSDR dongle
readsb_node: cluster-worker05
#the node hostname, from the inventory file, that has 978 RTLSDR dongle
dump1090_node: cluster-worker05

airband_node: cluster-worker06

#metal-lb version to install
metallb_version: v0.9.5

# All persistent data is stored on a NFS share
# IP and path on the NFS share for workloads

nfs_share_ip: "192.168.31.16"
nfs_share_path: "/volume1/cluster"

# Below are the individual workloads to install. Change the values to match your install. 
# Set xxxx_install to true if you want the service enabled
# Some containers will be forced on to make config easier until I figure out a better way
# influxdb, MLAT and readsb will ALWAYS NEED be on
# I will have variables for installing them or not, but don't change it unless you know what you are doing
# by know what you are doing means removing/changing enviornment variables in the role files

## Additionally, sbs port is forced to 30003
## beast is always going to be 30005

# Values for ALL workloads

timezone: "America\\Denver" # Time zone
# site latitude/longitude
lat: "35.18808"
lon: "-106.56953"
# site altitude
# some containers need the altitude without units
alt_with_units: "5299ft"
alt_without_units: "5299" # in feet
alt_meters: "1615"

## workload IPs
cloudflared_ip: "192.168.31.213"
guac_ip: "192.168.31.208"
pihole_ip: "192.168.31.210"
transmission_ip: "192.168.31.211"

adsb_host: "192.168.31.212" # host running readsb
uat_host: "192.168.31.219"
mlat_host: "192.168.31.218"
adsbexchange_ip: "192.168.31.220"
fr24_ip: "192.168.31.216"
influxdb_ip: "192.168.31.221"
piaware_ip: "192.168.31.217"
planefinder_ip: "192.168.31.222"
tar1090_ip: "192.168.31.214"
airband_ip: "192.168.31.223"

# workload secrets

adsbhub_clientkey: |
                  {% raw %}
                  secret
                  {% endraw %}
adsbexchange_uuid: "secret"
adsbexchange_site_name: "secret"
opensky_serial: "secret"
opensky_username: "secret"
fr24_key: "secret"
planefinder_sharecode: "secret"
piaware_feeder_id: "secret"
transmission_pass: "secret"
pihole_webpassword: "secret"
airband_admin_password: "secret"

# workload ports
# for some reason EVs require the port to be set as text.
# Any that do require that are set in quotes. Ensure same as none text variable

adsbexchange_mlat_port: 30105
dump978_rawuat_port: 30978
dump978_json_port: 30979
dump978_rawout_port: 37981
fr24_web_port: 80
fr24_base_port: 30003
fr24_raw_port: 30334
airband_port: 8000
mlat_out_port: 30105
mlat_out_port_text: "30105"
piaware_web_port: 80
piaware_basestation_port: 30003
piaware_beastout_port: 30005
piaware_mlat_port: 30105
piaware_uatraw_port: 30978
piaware_uatjson_port: 30979
planefinder_web_port: 80
planefinder_echo_port: 30054
readsb_web_port: 80
readsb_rawin_port: 30001
readsb_rawout_port: 30002
readsb_sbs_port: 30003
readsb_sbs_text_port: "30003" 
readsb_beastin_port: 30004
readsb_beastout_port: 30005
readsb_beastout_text_port: "30005"
readsb_beastin_other_port: 30104
readsb_influxsb_url: "http://{{ influxdb_ip }}:8086"
tar1090_web_port: 80

##-------NON ADSB-------##

# cloudflared

cloudflared_install: true

cloudflared_image: "crazymax/cloudflared"

# guacamole

guac_install: true
guac_image: "oznu/guacamole:armhf"


pihole_install: true
pihole_image: "pihole/pihole"
pihole_dns: "192.168.31.212#5353"

transmission_install: true
transmission_image: "linuxserver/transmission"


transmission_data_path: "/volume1/Cluster-Plex"
transmission_media_path: "/volume1/Media"

# metallb
# ONLY ALTER THE LAST LINE
# all workload IPs NEED to fall within the range of IPs metallb below
metallb_config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.31.200-192.168.31.250
# you can change this if you want. You don't have to
# if you do, look in to generating the secret key manually
metallb_secretkey: |
                  {% raw %}
                  Y25TMG5qNWMzYm1VeERheDJTVjM1aVlybWVzblpEZ1BKVDQ1L3BPc2JDRXdaSHZ1Nkg4VVB6eEtSdStacVNuawpWUXBkZzRoL00xaW9GRW1kWWRQYTg3cUYyQ0RDS0RaUHZJamhDL0Z6MTZZYVd2clhMSGQ5Q1lmRWEreEZLalE2CmdvbGFkcWtiOVJ5b01CbHpNeHQ1dW8yZDBSelRUc09JampXc3QyenRiNTA9
                  {% endraw %}

##-------ADSB Master Workloads--------## 

# dump978

dump978_install: true
dump978_image: "mikenye/dump978:latest"
dump978_serial: "00001000"

# mlat
mlat_install: true
# set each IP address of containers that provide MLAT. Currently piaware, adsbx do.
# remove any unused feeders
mlat_net_connector: "{{ piaware_ip }},{{ piaware_mlat_port }},beast_in;{{ adsbexchange_ip }},{{ adsbexchange_mlat_port }},beast_in"

# readsb

readsb_install: true
readsb_image: "mikenye/readsb-protobuf"
readsb_device_type: "rtlsdr"
readsb_serial: "00000111"
# mlat and 978 host IPs
readsb_net_connector: "{{ mlat_host }},{{ mlat_out_port }},beast_in;{{ uat_host }},{{ dump978_rawout_port }},raw_in"

##-------ADSB Feeder and Misc Workloads--------##

## ADSB Hub

adsbhub_install: true
adsbhub_image: "mikenye/adsbhub"

# ADSB Exchange

adsbexchange_install: true
adsbexchange_image: "mikenye/adsbexchange"

airband_install: true
airband_image: "fredclausen/rtlsdrairband:latest"
airband_hostname: "192.168.31.223"
airband_station1_type: "rtlsdr"
airband_station1_gain: "26"
airband_station1_mode: "scan"
airband_station1_freqs: "123.9, 124.325, 125.45, 127.4, 124.4, 134.8, 133.65, 132.8, 126.3"
airband_station1_serial: "00013475"
airband_station1_server: "127.0.0.1"
airband_station1_mountpoint: "KABQ.mp3"
airband_station1_name: "Albuquerque ATC"
airband_station1_genre: "Aviation"

# Flight Radar 24

fr24_install: true
fr24_image: "mikenye/fr24feed:1.0.25-3_armhf_arm64"
fr24_mlat_enable: "yes"


# influx db

influxdb_install: true
influxdb_image: "docker.io/influxdb"

# opensky

opensky_install: true
opensky_image: "mikenye/opensky-network"

# piaware/flight aware

piaware_install: true
piaware_image: "mikenye/piaware:uat_support_preview"

# plane finder

planefinder_install: true
planefinder_image: "mikenye/planefinder"

# tar10190

tar1090_install: true
tar1090_image: "mikenye/tar1090"
