---
# default user for the nodes. Must have SSH key-less login on the machine running the playbook
# and must have sudo password-less enabled on the host(s)

#  when: adsbexchange_install == true

ansible_user: ubuntu

# install misc services?

install_misc_services: true
install_adsb_services: true

#for use when running setup-pods-master. Fill in values from the rancher setup
rancher_token: "fhkp442xsc6c7ddv7vrqhhntcgbxqgr4mfjbczwjwkbx5wvq579dj9"
rancher_checksum: "15e3e28a2dd4deb1d657ab3d9c01a501a5d7978dfbcff0ba5710819d85a00079"
rancher_server: https://192.168.31.30:8443
rancher_image: rancher/rancher:v2.5.1
rancher_agent: rancher/rancher-agent:v2.5.1

#the node hostname, from the inventory file, that has 1090 RTLSDR dongle
readsb_node: cluster-worker05
#the node hostname, from the inventory file, that has 978 RTLSDR dongle
dump1090_node: cluster-worker05

#metal-lb version to install
metallb_version: v0.9.4

# All persistent data is stored on a NFS share
# IP and path on the NFS share for workloads

nfs_share_ip: "192.168.31.16"
nfs_share_path: "/volume1/cluster"

# Below are the individual workloads to install. Change the values to match your install. 
# Set xxxx_install to true if you want the service enabled
# Some containers will be forced on to make config easier until I figure out a better way
# influxdb, MLAT and readsb will ALWAYS NEED be on
# I will have variables for installing them or not, but don't change it unless you know what you are doing
# by know what you are doing means removing/changing enviornment variables in the role files

## Additionally, sbs port is forced to 30003
## beast is always going to be 30005

# Values for ALL workloads

timezone: "America\\Denver" # Time zone
adsb_host: "192.168.31.212" # host running readsb
uat_host: "192.168.31.219"
mlat_host: "192.168.31.218"
sbsport: "30003"
# site latitude/longitude
lat: "35.00000"
lon: "-106.00000"
# site altitude
# some containers need the altitude without units
alt_with_units: "5299ft"
alt_without_units: "5299" # in feet
alt_meters: "1615"

##-------NON ADSB-------##

# cloudflared

cloudflared_install: true
cloudflared_ip: "192.168.31.213"
cloudflared_image: "crazymax/cloudflared"

# guacamole

guac_install: true
guac_image: "oznu/guacamole:armhf"
guac_ip: "192.168.31.208"

pihole_install: true
pihole_image: "pihole/pihole"
pihole_dns: "192.168.31.212#5353"
pihole_webpassword: "secret"
pihole_ip: "192.168.31.210"

transmission_install: true
transmission_image: "linuxserver/transmission"
transmission_pass: "secret"
transmission_ip: "192.168.31.211"
transmission_data_path: "/volume1/Cluster-Plex"
transmission_media_path: "/volume1/Media"

# metallb
# ONLY ALTER THE LAST LINE
# all workload IPs NEED to fall within the range of IPs metallb below
metallb_config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.31.200-192.168.31.250
# you can change this if you want. You don't have to
# if you do, look in to generating the secret key manually
metallb_secretkey: |
                  {% raw %}
                  secret
                  {% endraw %}

##-------ADSB Master Workloads--------## 

# dump978

dump978_install: true
dump978_image: "mikenye/dump978:latest"
dump978_serial: "00001000"

# mlat
mlat_install: true
mlat_image: "mikenye/readsb-protobuf:beta"
# set each IP address of containers that provide MLAT. Currently FR24, piaware, adsbx do.
# remove any unused feeders
mlat_net_connector: "192.168.31.216,30003,beast_in;192.168.31.217,30104,beast_in;192.168.31.220,30105,beast_in"

# readsb

readsb_install: true
readsb_image: "mikenye/readsb-protobuf:beta"
readsb_device_type: "rtlsdr"
readsb_serial: "00000111"
# mlat and 978 host IPs
readsb_net_connector: "192.168.31.218,30105,beast_in;192.168.31.219,37981,raw_in"

##-------ADSB Feeder and Misc Workloads--------##

## ADSB Hub

adsbhub_install: true
adsbhub_clientkey: |
                  {% raw %}
                  secret
                  {% endraw %}
adsbhub_image: "mikenye/adsbhub"

# ADSB Exchange

adsbexchange_install: true
adsbexchange_uuid: "secret"
adsbexchange_site_name: "Fred-House"
adsbexchange_image: "mikenye/adsbexchange"
adsbexchange_ip: "192.168.31.220"

# Flight Radar 24

fr24_install: true
fr24_image: "mikenye/fr24feed:1.0.25-3_armhf_arm64"
fr24_key: "secret"
fr24_ip: "192.168.31.216"

# influx db

influxdb_install: true
influxdb_image: "docker.io/influxdb"
influxdb_ip: "192.168.31.221"

# opensky

opensky_install: true
opensky_image: "mikenye/opensky-network"
opensky_serial: "secret"
opensky_username: "secret"

# piaware/flight aware

piaware_install: true
piaware_image: "mikenye/piaware:uat_support_preview"
piaware_feeder_id: "secret"
piaware_ip: "192.168.31.217"

# plane finder

planefinder_install: true
planefinder_image: "mikenye/planefinder"
planefinder_sharecode: "secret"
planefinder_ip: "192.168.31.222"

# tar10190

tar1090_install: true
tar1090_image: "mikenye/tar1090"
tar1090_ip: "192.168.31.214"
