---
- name: Deploy ADSB Hub
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: adsbhub
        namespace: adsb
        labels:
          app: adsbhub
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: adsbhub
        template:
          metadata:
            labels:
              app: adsbhub
          spec:
            hostname: "{{ adsbhub_host }}"
            containers:
            - name: adsbhub
              image: "{{ adsbhub_image }}"
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: SBSHOST
                value: "{{ adsb_host }}"
              - name: CLIENTKEY
                value: "{{ adsbhub_clientkey }}"
              - name: SBSPORT
                value: "{{ readsb_sbs_text_port }}"