---
- name: Download MetalLB Remote Namespace Config
  get_url: 
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/namespace.yaml"
    dest: "{{ role_path }}/files/"

- name: Download MetalLB Remote Config
  get_url: 
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/metallb.yaml"
    dest: "{{ role_path }}/files/"

- name: Deploy MetalLB Namespace
  k8s:
    state: "{{ workload_state }}"
    src: "{{ role_path }}/files/namespace.yaml"

- name: Deploy MetalLB
  k8s:
    state: "{{ workload_state }}"
    src: "{{ role_path }}/files/metallb.yaml"

- name: Deploy MetalLB Secret Key
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
      data:
        secretkey: "{{ metallb_secretkey }}"

- name: Deploy MetalLB Config
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: "{{ metallb_config }}"