---
- name: Test for Raspbian
  set_fact:
    raspbian: '{% if
      ( ansible_facts.architecture is search("arm") and
        ansible_facts.lsb.description is match("[Rr]aspbian.*[Bb]uster") ) or
      ( ansible_facts.architecture is search("aarch64") and
        ansible_facts.lsb.description is match("Debian.*buster") or
        ansible_facts.lsb.description is match("[Rr]aspbian.*[Bb]uster") ) %}true{% else %}false{% endif %}'

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
  when:
    - raspbian is true
