---
- name: Deploy Plane Watch
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: planewatch
        namespace: adsb
        labels:
          app: planewatch
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: planewatch
        template:
          metadata:
            labels:
              app: planewatch
          spec:
            hostname: "{{ planewatch_host }}"
            containers:
            - name: planewatch
              image: planewatch/plane-watch
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: BEASTHOST
                value: "{{ adsb_host }}"
              - name: BEASTPORT
                value: "{{ readsb_beastout_text_port }}"
              - name: API_KEY
                value: 094e6620-b937-47fb-9e34-5a5a4f93ad63