---
- name: Deploy Cloud Flared
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflared
        namespace: dns
        labels:
          app: cloudflared
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: cloudflared
        template:
          metadata:
            labels:
              app: cloudflared
          spec:
            hostname: "{{ cloudflared_host }}"
            containers:
            - name: pihole
              image: "{{ cloudflared_image }}"
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: TUNNEL_DNS_UPSTREAM
                value: "https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
              - name: TUNNEL_DNS_PORT
                value: "5353"
              ports:
              - name : dns
                protocol : UDP
                containerPort: 5353
              - name: metrics
                protocol: TCP
                containerPort: 49312


- name: Deploy Cloud Flared Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ cloudflared_host }}"
        namespace: dns
      spec:
        loadBalancerIP: "{{ cloudflared_ip }}"
        selector:
          app: cloudflared
        ports:
        - protocol: UDP
          port: 5353
          targetPort: 5353
          name : dns
        type: LoadBalancer
