---
- name: Deploy tar1090
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tar1090
        namespace: adsb
        labels:
          app: tar1090
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: tar1090
        template:
          metadata:
            labels:
              app: tar1090
          spec:
            hostname: "{{ tar1090_host }}"
            containers:
            - name: tar1090
              image: "{{ tar1090_image }}"
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: LAT
                value: "{{ lat }}"
              - name: LONG
                value: "{{ lon }}"
              - name: BEASTHOST
                value: "{{ adsb_host }}"
              - name: BEASTPORT
                value: "{{ readsb_beastout_text_port }}"
              - name: MLATHOST
                value: "{{ mlat_host }}"
              - name: MLATPORT
                value: "{{ mlat_out_port_text }}"
              - name: HEYWHATSTHAT_PANORAMA_ID
                value: "NN6R7EXG"
              - name: TAR1090_ENABLE_AC_DB
                value: "true"
              ports:
              - name: web
                containerPort: 80
              volumeMounts:
              - mountPath: /var/globe_history
                name: readsb-run
                subPath: tar1090
            volumes:
            - name: readsb-run
              persistentVolumeClaim:
                claimName: readsb-run

- name: Deploy tar1090 Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ tar1090_host }}"
        namespace: adsb
      spec:
        loadBalancerIP: "{{ tar1090_ip }}"
        selector:
          app: tar1090
        ports:
        - protocol: TCP
          port: "{{ tar1090_web_port }}"
          targetPort: 80
          name : web
        type: LoadBalancer 