
---
- name: Deploy node-red
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: node-red
        namespace: default
        labels:
          app: node-red
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: node-red
        template:
          metadata:
            labels:
              app: node-red
          spec:
            containers:
            - name: node-red
              image: "fredclausen/node-red-ha:latest"
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "America/Denver"
              volumeMounts:
                - mountPath: /data
                  name: readsb-run
                  subPath: node-red
            volumes:
            - name: readsb-run
              persistentVolumeClaim:
                claimName: readsb-run

- name: Deploy rest980 service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: node-red
        namespace : default
      spec:
        loadBalancerIP: 192.168.31.205
        selector:
          app: node-red
        ports:
        - protocol: TCP
          port: 1880
          targetPort: 1880
          name : output
        type: LoadBalancer