---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: raspbian
    - role: ubuntu
    - role: initial-server-setup
    - role: docker

- hosts: nutmaster
  gather_facts: yes
  become: yes
  roles:
    - role: nut-master

- hosts: nutslave
  gather_facts: yes
  become: yes
  roles:
    - role: nut-slave