---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: raspbian
    - role: ubuntu
    - role: initial-server-setup
    - role: docker

- hosts: nut-master
  gather_facts: yes
  become: yes
  roles:
    - role: nut-master

- hosts: nut-slave
  gather_facts: yes
  become: yes
  roles:
    - role: nut-slave

- hosts: rancher
  gather_facts: yes
  become: yes
  roles:
    - role: rancher