---
- name: label node with RTLSDR dongle for readsb
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels:
          dump1090: "usb"
        name: "{{ dump1090_node }}"

- name: Deploy dump978
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dump978
        namespace: default
        labels:
          app: dump978
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: dump978
        template:
          metadata:
            labels:
              app: dump978
          spec:
            nodeSelector:
              dump1090: usb
            containers:
            - name: dump978
              image: "{{ dump978_image }}"
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: DUMP978_RTLSDR_DEVICE
                value: "{{ dump978_serial }}"
              - name: DUMP978_SDR_PPM
                value: "2"
              ports:
              - name : raw-uat
                containerPort: 30978
              - name : json
                containerPort: 30979
              - name : raw-out
                containerPort: 37981
              volumeMounts:
              - mountPath: /dev/bus/
                name: usb
            volumes:
            - name: usb
              hostPath:
                path: /dev/bus/
                
- name: Deploy dump978 service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: dump978
        namespace : default
      spec:
        loadBalancerIP: "{{ uat_host }}"
        selector:
          app: dump978
        ports:
        - protocol: TCP
          port: "{{ dump978_rawuat_port }}"
          targetPort: 30978
          name : raw-uat
        - protocol: TCP
          port: "{{ dump978_json_port }}"
          targetPort: 30979
          name : json
        - protocol: TCP
          port: "{{ dump978_rawout_port }}"
          targetPort: 37981
          name : rawout
        type: LoadBalancer
