---
- name: label node with RTLSDR dongle for ADSB
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels:
          readsb: "usb"
        name: "{{ readsb_node }}"
        namespace: adsb

- name: Deploy readsb-protobuf
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: readsb
        namespace: adsb
        labels:
          app: readsb
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: readsb
        template:
          metadata:
            labels:
              app: readsb
          spec:
            hostname: "{{ adsb_host }}"
            nodeSelector:
              readsb: usb
            containers:
            - name: readsb
              image: "{{ readsb_image }}"
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: READSB_LAT
                value: "{{ lat }}"
              - name: READSB_LON
                value: "{{ lon }}"
              - name: READSB_DEVICE_TYPE
                value: "{{ readsb_device_type }}"
              - name: READSB_FIX
                value: "true"
              - name: READSB_GAIN
                value: "autogain"
              - name: READSB_MODEAC
                value: "true"
              - name: READSB_RX_LOCATION_ACCURACY
                value: "2"
              - name: READSB_STATS_RANGE
                value: "true"
              - name: READSB_NET_ENABLE
                value: "true"
              - name: READSB_RTLSDR_DEVICE
                value: "{{ readsb_serial }}"
              - name: READSB_RTLSDR_PPM
                value: "0"
              - name: READSB_NET_CONNECTOR
                value: "{{ readsb_net_connector }}"
              - name: INFLUXDBURL
              #  value: "{{ readsb_influxsb_url }}"
                value: ""
              ports:
              - name: web
                containerPort: 8080
              - name : raw-input
                containerPort: 30001
              - name : raw-output
                containerPort: 30002
              - name : sbs-basestation
                containerPort: 30003
              - name : beast-in
                containerPort: 30004
              - name : beast-out
                containerPort: 30005
              - name : beast-in-alt
                containerPort: 30104
              volumeMounts:
              - mountPath: /run/readsb
                name: readsb-run
                subPath: readsb
              - mountPath: /run/autogain
                name: readsb-run
                subPath: autogain
              - mountPath: /run/collectd
                name: readsb-run
                subPath: collectd-readsb
              - mountPath: /dev/bus/
                name: usb
              - mountPath: /etc/mtab
                name: mtab
            volumes:
            - name: readsb-run
              persistentVolumeClaim:
                claimName: readsb-run
            - name: usb
              hostPath:
                path: /dev/bus/
            - name: mtab
              hostPath:
                path: /etc/mtab
                type: File               

- name: Deploy readsb-protobuf Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ adsb_host }}"
        namespace: adsb
      spec:
        loadBalancerIP: "{{ adsb_ip }}"
        selector:
          app: readsb
        ports:
        - protocol: TCP
          port: "{{ readsb_web_port }}"
          targetPort: 8080
          name : web
        - protocol: TCP
          port: "{{ readsb_rawin_port }}"
          targetPort: 30001
          name : rawin
        - protocol: TCP
          port: "{{ readsb_rawout_port }}"
          targetPort: 30002
          name : rawout
        - protocol: TCP
          port: "{{ readsb_sbs_port }}"
          targetPort: 30003
          name: sbs
        - protocol: TCP
          port: "{{ readsb_beastin_port }}"
          targetPort: 30004
          name: beastin
        - protocol: TCP
          port: "{{ readsb_beastout_port }}"
          targetPort: 30005
          name : beatout
        - protocol: TCP
          port: "{{ readsb_beastin_other_port }}"
          targetPort: 30104
          name : beastinother
        type: LoadBalancer 