
---
- name: Label node with RTLSDR dongle for ACARS Hub
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels:
          acarshub: "usb"
        name: "{{ acars_node }}"

- name: Deploy ACARS Hub
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: acarshub
        namespace: adsb
        labels:
          app: acarshub
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: acarshub
        template:
          metadata:
            labels:
              app: acarshub
          spec:
            hostname: "{{ acarshub_host }}"
            nodeSelector:
              acarshub: usb
            containers:
            - name: acarshub
              image: "fredclausen/acarshub:latest"
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: FREQS_ACARS
                value: "{{ acarshub_acars_freqs }}"
              - name: FREQS_VDLM
                value: "{{ acarshub_vdlm_freqs }}"
              - name: SERIAL
                value: "{{ acarshub_serial_acars }},,A36.0;{{ acarshub_serial_vdlm }},,A36.0"
              #- name: GAIN
              #  value:
              #- name: GAIN_ACARS
              #  value: "{{ acarshub_gain_acars }}"
              #- name: GAIN_VDLM
              #  value: "{{ acarshub_gain_vdlm }}"
              #- name: SERIAL_ACARS
              #  value: "{{ acarshub_serial_acars }}"
              #- name: SERIAL_VDLM
              #  value: "{{ acarshub_serial_vdlm }}"
              - name: STATION_ID_ACARS
                value: "{{ acarshub_stationid_acars }}"
              - name: STATION_ID_VDLM
                value: "{{ acarshub_stationid_vdlm }}"
              - name: ENABLE_VDLM
                value: "true"
              - name: ENABLE_ACARS
                value: "true"
              - name: ENABLE_WEB
                value: "true"
              - name: FEED
                value: "True"
              - name: QUIET_LOGS
                value: "True"
              - name: DEBUG_LOGGING
                value: ""
              - name: EXTREME_LOGGING
                value: ""
              - name: DB_SAVEALL
                value: ""
              - name: TAR1090_URL
                value: "tar1090"
              - name: IATA_OVERRIDE
                value: "UP|UPS|United Parcel Service;GS|FTH|Mountain Aviation (Foothills)"
              - name: ENABLE_ADSB
                value: "true"
              - name: ADSB_LAT
                value: "{{ lat }}"
              - name: ADSB_LON
                value: "{{ lon }}"
              - name: ADSB_URL
                value: "http://{{ tar1090_host }}/data/aircraft.json"
              volumeMounts:
              - mountPath: /run/acars
                name: acarshub-volume
                subPath: acars
              - mountPath: /dev/bus/
                name: usb
            volumes:
            - name: acarshub-volume
              persistentVolumeClaim:
                claimName: acarshub-pvc
            - name: usb
              hostPath:
                path: /dev/bus/
- name: Deploy ACARS Hub Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ acarshub_host }}"
        namespace: adsb
      spec:
        loadBalancerIP: "{{ acarshub_ip }}"
        selector:
          app: acarshub
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          name : output
        type: LoadBalancer