---
- name: Deploy MLAT
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mlat
        namespace: adsb
        labels:
          app: mlat
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: mlat
        template:
          metadata:
            labels:
              app: mlat
          spec:
            hostname: "{{ mlat_host }}"
            containers:
            - name: mlat
              image: "{{ readsb_image }}"
              imagePullPolicy: Always
              env:
              - name: VERBOSE_LOGGING
                value: "true"
              - name: TZ
                value: "{{ timezone }}"
              - name: READSB_FORWARD_MLAT
                value: "true"
              - name: READSB_NET_ENABLE
                value: "true"
              - name: DISABLE_WEBAPP
                value: "true"
              - name: DISABLE_PERFORMANCE_GRAPHS
                value: "true"
              - name: READSB_NET_ONLY
                value: "true"
              - name: READSB_NET_BEAST_OUTPUT_PORT
                value: "30105"
              - name: READSB_NET_CONNECTOR
                value: "{{ mlat_net_connector }}"
              ports:
              - name : mlat
                containerPort: "{{ mlat_out_port }}"

- name: Deploy MLAT Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ mlat_host }}"
        namespace: adsb
      spec:
        loadBalancerIP: "{{ mlat_ip }}"
        selector:
          app: mlat
        ports:
        - protocol: TCP
          port: "{{ mlat_out_port }}"
          targetPort: "{{ mlat_out_port }}"
          name : beast
        type: LoadBalancer 