---
- name: Deploy Web Proxy
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webproxy
        namespace: services
        labels:
          app: webproxy
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: webproxy
        template:
          metadata:
            labels:
              app: webproxy
          spec:
            hostname: webproxy
            containers:
            - name: webproxy
              image: kx1t/webproxy:latest
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: AUTOGENERATE
                value: "ON"
              - name: VERBOSELOG
                value: "OFF"
              - name: REVPROXY
                value: 
                  readsb|http://192.168.31.212,
                  piaware|http://192.168.31.217,
                  tar1090|http://192.168.31.214,
                  ajax|http://192.168.31.214/ajax,
                  assets|http://192.168.31.214/assets,
                  graphs|http://192.168.31.214/graphs,
                  radar|http://192.168.31.214/radar,
                  acarshub|http://192.168.31.226,
                  acarshubtest|http://192.168.31.28:8080
              ports:
              - name: web
                containerPort: 80
              volumeMounts:
              - mountPath: /run/nginx
                name: guac
                subPath: webproxy
            volumes:
            - name: guac
              persistentVolumeClaim:
                claimName: guac-run

- name: Deploy Web Proxy Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "webproxy"
        namespace : services
      spec:
        loadBalancerIP: 192.168.31.202
        selector:
          app: webproxy
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          name : web
        type: LoadBalancer 