---
- name: Deploy Plane Finder
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: planefinder
        namespace: adsb
        labels:
          app: planefinder
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: planefinder
        template:
          metadata:
            labels:
              app: planefinder
          spec:
            hostname: "{{ planefinder_host }}"
            containers:
            - name: planefinder
              image: "{{ planefinder_image }}"
              imagePullPolicy: Always
              env:
              - name: TZ
                value: "{{ timezone }}"
              - name: BEASTHOST
                value: "{{ adsb_host }}"
              - name: SHARECODE
                value: "{{ planefinder_sharecode }}"
              - name: LAT
                value: "{{ lat }}"
              - name: LONG
                value: "{{ lon }}"
              ports:
              - name: web
                containerPort: 30053
              - name: echo
                containerPort: 30054

- name: Deploy Plane Finder Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ planefinder_host }}"
        namespace: adsb
      spec:
        loadBalancerIP: "{{ planefinder_ip }}"
        selector:
          app: planefinder
        ports:
        - protocol: TCP
          port: "{{ planefinder_web_port }}"
          targetPort: 30053
          name : beast
        - protocol: TCP
          port: "{{ planefinder_echo_port }}"
          targetPort: 30054
          name : echo
        type: LoadBalancer 