
---
- name: Label node with Z-Wave Dongle
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels:
          homeassistant: "usb"
        name: "{{ homeassistant_node }}"

- name: Deploy Home Assistant
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: homeassistant
        namespace : homeautomation
        labels:
          app: homeassistant
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: homeassistant
        template:
          metadata:
            labels:
              app: homeassistant
          spec:
            hostNetwork: false
            nodeSelector:
              homeassistant: usb
            containers:
            - name: homeassistant
              image: "homeassistant/raspberrypi4-homeassistant:stable"
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
              - name: TZ
                value: "America/Denver"
              volumeMounts:
                - mountPath: /config
                  name: homeautomation-run
                  subPath: homeassistant
                - mountPath: /dev/
                  name: usb
                - mountPath: /sys
                  name: sys
            volumes:
            - name: homeautomation-run
              persistentVolumeClaim:
                claimName: homeautomation-run
            - name: usb
              hostPath:
                path: /dev/
            - name: sys
              hostPath:
                path: /sys/
- name: Deploy Home Assistant Service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ homeassistant_host }}"
        namespace : homeautomation
      spec:
        loadBalancerIP: 192.168.31.204
        selector:
          app: homeassistant
        ports:
        - protocol: TCP
          port: 8123
          targetPort: 8123
          name : output
        type: LoadBalancer