---
- name: Deploy icecast
  k8s:
    state: "{{ workload_state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: icecast
        namespace: default
        labels:
          app: icecast
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: icecast
        template:
          metadata:
            labels:
              app: icecast
          spec:
            containers:
            - name: icecast
              image: "{{ icecast_image }}"
              imagePullPolicy: Always
              ports:
              - name : api
                containerPort: 8000
              env:
              - name: ICECAST_SOURCE_PASSWORD
                value: "{{ icecast_source_password }}"
              - name: ICECAST_ADMIN_PASSWORD
                value: "{{ icecast_admin_password }}"
              - name: ICECAST_PASSWORD
                value: "{{ icecast_password }}"
              - name: ICECAST_RELAY_PASSWORD
                value: "{{ icecast_relay_password }}"
              - name: ICECAST_HOSTNAME
                value: "{{ icecast_hostname }}"

- name: Deploy icecast service
  k8s:
    state: "{{ workload_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: icecast
        namespace : default
      spec:
        loadBalancerIP: "{{ icecast_ip }}"
        selector:
          app: icecast
        ports:
        - protocol: TCP
          port: "{{ icecast_port }}"
          targetPort: 8000
          name : output
        type: LoadBalancer 