---

- hosts: localhost
  gather_facts: no
  become: no

  pre_tasks:
  - name: Set workload facts
    set_fact:
      workload_state: absent
  roles:
    - role: metal-lb  

- name: Install Misc Services
  import_playbook: setup-cluster-services-misc.yaml
  when: install_misc_services == true

- name: Install ADSB services
  import_playbook: setup-cluster-services-adsb.yaml
  when: install_adsb_services == true