---
- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - role: readsb-proto
      when: readsb_install == true
    - role: dump978
      when: dump978_install == true
    - role: mlat
      when: mlat_install == true
    - role: piaware
      when: piaware_install == true
    - role: fr24
      when: fr24_install == true
    - role: opensky
      when: opensky_install == true
    - role: adsbx
      when: adsbexchange_install == true
    - role: planefinder
      when: planefinder_install == true
    - role: adsbhub
      when: adsbhub_install == true
    - role: tar1090
      when: tar1090_install == true    
    - role: influxdb
      when: influxdb_install == true
    - role: rtlsdr-airband
      when: airband_install == true
    - role: radarbox
      when: radarbox_install == true
    - role: rawflight
      when: rawflight_install == true
    - role: acarshub
      when: acarshub_install == true